### PR TITLE
Add String.Format

### PR DESCRIPTION
**Pull request by ishvedov**
## Description
Add String.Format function

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Signed-off-by: ishvedov ivan.shvedov@gmail.com

### CODE REVIEW

**Comment by josesimoes** [comment]
Was testing this with the following code:

```
    public class Program
    {
        public static void Main()
        {
            try
            {
                DateTime date1 = new DateTime(2009, 7, 1);
                TimeSpan hiTime = new TimeSpan(14, 17, 32);
                double hiTemp = 62.1;
                TimeSpan loTime = new TimeSpan(3, 16, 10);
                double loTemp = 54.8;

                string result1 = String.Format("Temperature on {0:d}:\n{1,11}: {2} degrees (hi)\n{3,11}: {4} degrees (lo)",
                                               date1, hiTime, hiTemp, loTime, loTemp);
                Console.WriteLine(result1);
                Console.WriteLine("");

                string result2 = String.Format("Temperature on {0:d}:\n{1,11}: {2} degrees (hi)\n{3,11}: {4} degrees (lo)",
                                               new object[] { date1, hiTime, hiTemp, loTime, loTemp });
                Console.WriteLine(result2);


                Thread.Sleep(Timeout.InfiniteTimeSpan);
            }
            catch (Exception ex)
            {
                
            }
        }
    }
```

but it's throwing at me:
    #### Exception System.ArgumentException - 0x00000000 (1) ####
    #### Message: Format error: wrong simbol in {}
    #### System.String::Format [IP: 0153] ####
    #### NFApp327.Program::Main [IP: 006f] ####

**Comment by ishvedov** [comment]
Not implemented alignment. I'll make it today.

**Comment by josesimoes** [comment]
Oh... I see... for sure we won't need the full blown Format() so it's OK to have a lightweight version.
Just need to make it clear what is supported and what isn't.

**Comment by josesimoes** [comment]
After the latest commit I'm getting:

`Temperature on 07/01/2009:   14:17:32: 62.100000000000001 degrees (hi)   03:16:10: 54.799999999999997 degrees (lo)⠴`


Like I said above, because this is a constrained resource platform no one would be expected to see a fully implemented String.Format
I suggest we decide on what should be me available and concentrate on that. What do you think?

**Comment by ishvedov** [comment]
Problem with broken string.this[] in new firmwares. I wrote it in Slack

**Comment by ishvedov** [comment]
Wait for resolve nanoframework/Home#343

**Comment by josesimoes** [comment]
Blocked by nanoframework/Home#343.

**Comment by josesimoes** [comment]
The output is now the expected one:

```
hiTemp62.100000000000001
loTemp54.799999999999997
Temperature on 07/01/2009:
   14:17:32: 62.100000000000001 degrees (hi)
   03:16:10: 54.799999999999997 degrees (lo)
```

**Comment by josesimoes** [comment]
After nanoframework/nf-interpreter#743 the output is now 100% correct when compared with the full .NET output:

```
hiTemp62.1
loTemp54.8
Temperature on 07/01/2009:
   14:17:32: 62.1 degrees (hi)
   03:16:10: 54.8 degrees (lo)
```

**Comment by ishvedov** [comment]
I did it.

**Pull request merged**
