### PR TITLE
Fix typo in TimeSpan

### PR DESCRIPTION
**Pull request by Hassmann**
## Description
Miliseconds -> Milliseconds in code and documentation

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Signed-off-by: Hassmann <public@hassmann.com>

### CODE REVIEW

**Comment by josesimoes** [comment]
Please sign the CLA so this can be merged.

**Comment by Hassmann** [comment]
I signed it, didn't show up yet.

**Comment by josesimoes** [comment]
From the message above (from the CLA bot) it seems that there is a mismatch from the user that you've used for the commits and the user you've used to sign the CLA. Please change your email on GitHub account to the same that you've used when submitting those commits. You can do this with a secondary email or even changing temporarily your current email. 

You'll forgive these legalities but we have to be on the safe side... :smille:

**Comment by Hassmann** [comment]
I am very sorry, but the cla system continues to thank me for signing the agreement, only to keep the state at pending...

**Pull request merged**
